#!/usr/bin/env python3
"""Deterministic multi-frame presentation-session fixtures V1.

OFFLINE FIXTURES | PURE PRESENTATION | NO NETWORK | NO ORDERS

Every output frame is generated by DashboardPresentationSession. Nothing here
hand-writes the expected result state. These sequences exist for regression and
visual QA of poll-to-poll behavior.
"""
from __future__ import annotations

from typing import Any

from btc15_dashboard_presentation_session_v1 import DashboardPresentationSession

VERSION = "BTC15_DASHBOARD_SESSION_SEQUENCE_FIXTURES_V1"


def _combined(contract="C1", seconds=600.0, *, final_state="WATCH", final_side=None, final_fair=None):
    return {
        "contract": contract,
        "canonical_seconds_left": seconds,
        "up_bid": .44,
        "up_ask": .45,
        "down_bid": .55,
        "down_ask": .56,
        "early": {"state": "PASS", "side": None, "ask": None, "fair": None, "edge": None},
        "final": {"state": final_state, "side": final_side, "fair": final_fair},
    }


def _ui(
    *, contract="C1", lifecycle="ACTIVE", side="UP", opp=1, completed=0,
    scanning=False, app_ready=True, fresh=True, block=None,
    tier="IDEAL_25_35", entry=31.0, bid=34.0, gain=3.0, peak=3.0, giveback=0.0,
):
    return {
        "contract": contract,
        "lifecycle_state": lifecycle,
        "display_state": "WAIT" if not app_ready else lifecycle,
        "side": side,
        "opportunity_index": opp,
        "serial_opportunities_completed": completed,
        "scanning_for_next": scanning,
        "entry_guidance": {"tier": tier, "label": tier, "presentation_only": True},
        "entry_ask_c": entry,
        "current_bid_c": bid,
        "exec_gain_c": gain,
        "peak_exec_gain_c": peak,
        "giveback_from_peak_c": giveback,
        "source": {
            "app_ready": app_ready,
            "source_fresh": fresh,
            "integration_ready": app_ready,
            "block_reason": block,
            "fail_closed": not app_ready,
        },
        "watch_warning": {"visible": False, "certified": False},
        "numeric_flip_risk": {"visible": False, "value": None, "certified": False},
        "manual_execution_only": True,
        "orders": False,
        "order_action": None,
    }


def _compact(model: dict[str, Any], frame_name: str) -> dict[str, Any]:
    cards = model["cards"]
    scalp = cards["SCALP_OPPORTUNITY"]
    session = dict(model.get("presentation_session") or {})
    reducer = dict(model.get("session_reducer") or {})
    hist = dict(model.get("scalp_history_slot") or {})
    return {
        "frame": frame_name,
        "contract": model.get("contract"),
        "timer": cards["CONTRACT_TIME_LEFT"].get("primary"),
        "final_action": cards["FINAL_OUTCOME"].get("action"),
        "early_action": cards["EARLY_OPPORTUNITY"].get("action"),
        "scalp_action": scalp.get("action"),
        "scalp_primary": scalp.get("primary"),
        "scalp_lifecycle": scalp.get("underlying_lifecycle_state"),
        "opportunity_index": scalp.get("opportunity_index"),
        "entry_context": (model.get("manual_entry_context") or {}).get("state"),
        "source_fail_closed": session.get("current_fail_closed") is True,
        "scalp_quarantined": reducer.get("scalp_frame_quarantined") is True,
        "quarantine_reason": reducer.get("quarantine_reason"),
        "history_visible": hist.get("visible") is True,
        "history_headline": hist.get("headline"),
        "manual_position_confirmed": False,
        "orders": False,
    }


def _run(frames):
    session = DashboardPresentationSession()
    out = []
    for name, combined, ui in frames:
        out.append(_compact(session.process(combined, ui), name))
    return out


def build_sequences() -> dict[str, list[dict[str, Any]]]:
    acceptable_recovery = _run([
        ("VALID_ENTRY", _combined(seconds=600), _ui(entry=31.0, tier="IDEAL_25_35")),
        ("SOURCE_STALE", _combined(seconds=580), _ui(app_ready=False, fresh=False, block="SCALP SOURCE STALE", tier="UNAVAILABLE", entry=None)),
        ("RECOVER_PROTECT", _combined(seconds=560), _ui(lifecycle="PROTECT", tier="UNAVAILABLE", entry=None, bid=40.0, gain=9.0, peak=10.0, giveback=1.0)),
    ])

    tracking_recovery = _run([
        ("DONT_CHASE", _combined(seconds=600), _ui(entry=71.0, bid=72.0, tier="CAUTION_ABOVE_50")),
        ("SOURCE_STALE", _combined(seconds=580), _ui(app_ready=False, fresh=False, block="SCALP SOURCE STALE", tier="UNAVAILABLE", entry=None)),
        ("BACKEND_PROTECT_STILL_TRACKING", _combined(seconds=550), _ui(lifecycle="PROTECT", tier="UNAVAILABLE", entry=None, bid=78.0, gain=7.0, peak=10.0, giveback=3.0)),
    ])

    regression_quarantine = _run([
        ("ACTIVE", _combined(seconds=600), _ui()),
        ("PROTECT", _combined(seconds=540), _ui(lifecycle="PROTECT", bid=40.0, gain=9.0, peak=10.0, giveback=1.0)),
        ("OUT_OF_ORDER_ACTIVE", _combined(seconds=500, final_state="LOCK", final_side="UP", final_fair=.94), _ui(lifecycle="ACTIVE", bid=39.0, gain=8.0, peak=10.0, giveback=2.0)),
    ])

    rollover = _run([
        ("OLD_EXIT", _combined("C1", 1.0), _ui(contract="C1", lifecycle="EXIT", entry=31.0, bid=37.0, gain=6.0, peak=11.0, giveback=5.0)),
        ("NEW_CONTRACT", _combined("C2", 899.0), _ui(contract="C2", lifecycle="PASS", side=None, opp=None, completed=0, scanning=False, tier="UNAVAILABLE", entry=None, bid=None, gain=None, peak=None, giveback=None)),
    ])

    serial_handoff = _run([
        ("SCALP_1_EXIT", _combined(seconds=400), _ui(lifecycle="EXIT", opp=1, completed=1, entry=31.0, bid=37.0, gain=6.0, peak=11.0, giveback=5.0)),
        ("SCAN_2", _combined(seconds=390), _ui(lifecycle="PASS", side=None, opp=None, completed=1, scanning=True, tier="UNAVAILABLE", entry=None, bid=None, gain=None, peak=None, giveback=None)),
        ("SCALP_2_ACTIVE", _combined(seconds=370), _ui(lifecycle="ACTIVE", opp=2, completed=1, entry=42.0, bid=44.0, gain=2.0, peak=2.0, giveback=0.0, tier="GOOD_36_50")),
    ])

    return {
        "ACCEPTABLE_STALE_RECOVERY": acceptable_recovery,
        "TRACKING_STALE_RECOVERY": tracking_recovery,
        "PROTECT_REGRESSION_QUARANTINE": regression_quarantine,
        "CONTRACT_ROLLOVER": rollover,
        "SERIAL_HANDOFF": serial_handoff,
    }


SEQUENCES = build_sequences()

__all__ = ["VERSION", "SEQUENCES", "build_sequences"]
