"""Bounded OFFLINE timing of actual frozen native functions; no network/order path.

Fixtures exercise 35 days of candle history and 20 minutes of native BTC ticks.
This is not a reconstruction of production CPU contention, disk or pending load.
"""
import json
import statistics
import tempfile
import time
from pathlib import Path
from collections import defaultdict, deque
import numpy as np
import pandas as pd
from completion_audit.isolated_decision_v2 import FrozenRuntime
from test_btc15_isolated_decision_v2 import completed, fixture, OPEN
from test_btc15_ladder_completion_v1 import frame
from btc15_ladder_product_v1 import Directional
from btc15_ladder_journal_v1 import Journal, atomic_json
import btc15_information_native_offpath_candidate as native


def run():
    samples=defaultdict(list)
    def measure(name, fn, *args, **kwargs):
        start=time.perf_counter()
        try:return fn(*args, **kwargs)
        finally:samples[name].append((time.perf_counter()-start)*1000)
    index=pd.date_range(end='2019-12-31T23:49Z',periods=35*1440,freq='min')
    values=np.full(len(index),100000.)
    history=pd.DataFrame(dict(Open=values,High=values+2,Low=values-2,Close=values,
                              Volume=1.,source_utc=index),index=index)
    runtime=FrozenRuntime(pd.concat([history,completed()]))
    for name in ('_fair_frame_at_cut','_fair_build_snapshot','_live_fair_shadow',
                 'log_early_conf_shadow','log_unified_subminute','update_pending',
                 '_update_true_scalp_pending','_update_profit_shadow',
                 '_maybe_true_scalp_signal','maybe_create_event'):
        original=runtime.ns[name]
        runtime.ns[name]=lambda *a,_fn=original,_name=name,**k:measure(_name,_fn,*a,**k)
    for name in ('_fair_rf','_fair_sigmoid'):
        model=runtime.ns[name]; original=model.predict_proba
        model.predict_proba=lambda *a,_fn=original,_name=name,**k:measure(_name+'.predict_proba',_fn,*a,**k)
    runtime.ns['_ec_btc_ticks']=deque((pd.Timestamp(OPEN+i-.1,unit='s',tz='UTC'),
        pd.Timestamp(OPEN+i-.05,unit='s',tz='UTC'),100080.) for i in range(-900,300,5))
    with tempfile.TemporaryDirectory() as td:
        native.COHORT_PATH=Path(td)/'cohort.jsonl'
        exporter=native.NativeExport(clock=lambda:runtime.at)
        engine=Directional();engine.restore({})
        journal=Journal(Path(td)/'main.sqlite3','main')
        for i in range(40):
            output=measure('complete_native_loop_offline',runtime.step,fixture(300+5*i))
            if any('WARNING' in msg for msg in output['messages']):
                raise AssertionError(output['messages'])
            measure('information_anchor_offer',exporter.offer,runtime.ns)
            measure('cohort_serialization_flush_fsync',native.cohort_offer,runtime.ns)
            f=frame(offset=300+5*i,sequence=i+1)
            record,state,view=measure('Directional.process',engine.process,f,f['captured_ts']+.01)
            measure('journal_commit',journal.commit,record,state)
            measure('atomic_view_fsync',atomic_json,Path(td)/'main.json',view)
        journal.close()
    result=dict(schema='BTC15_OFFLINE_STAGE_TIMING_V1',samples=40,candle_rows=len(runtime.ns['_fair_btc']),
        native_tick_count=len(runtime.ns['_ec_btc_ticks']),network='IN_MEMORY_ADAPTERS',
        stages_ms={k:dict(count=len(v),median=statistics.median(v),p95=sorted(v)[int(.95*(len(v)-1))],
                         maximum=max(v)) for k,v in sorted(samples.items())},
        limitations=['No production resource contention or original 49 stall snapshots',
                    'Native pending lifecycle load is generated by synthetic tape, not historical production backlog',
                    'Filesystem is local scratch, not Railway mounted volume'],
        optimization_selected=False,
        decision='Do not attribute historical 9.322–24.470s delays to an inner operation from this replay. Ship stage accounting; no speculative performance optimization.',
        signal_only=True,orders=False)
    path=Path('qualification/v2_product_20261004/stage_timing_before_changes.json')
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result,indent=2))

if __name__=='__main__':run()
